In [1]:
# Dependencies
    #import pandas as pd
#Setting Datasets
#df = "Resources/OL2010_2013.csv"
    #combine1 = "Resources/OL2014_2015.csv"
    #combine2 = "Resources/TE2010_2015.csv"
#Loading into DataFrame
#df = pd.read_csv(df, encoding="utf-8")
    #combine1 = pd.read_csv(combine1, encoding="utf-8")
    #combine2 = pd.read_csv(combine2, encoding="utf-8")

import pandas as pd

df = "Resources/OL2010_2013.csv"
df = pd.read_csv(df, encoding="utf-8")

filenames = ["Resources/OL2014_2015.csv", "Resources/TE2010_2015.csv", 
             "Resources/WR2010_2013.csv", "Resources/WR2014_2015.csv"]

for filename in filenames:
    df = df.append(pd.read_csv(filename), ignore_index=True)

df['Pos'] = df['Pos'].replace({'OG': 'OL', 'OT': 'OL'})

df.head()

,Rk,Year,Player,Pos,AV,School,College,HE,Height,Wt,40YD,Vertical,BenchReps,Broad Jump,3Cone,Shuttle,Drafted (tm/rnd/yr)
0,1,2013,Brian Winters,OL,27,Kent State,NaN,4-Jun,6'4,320,5.22,NaN,9,NaN,NaN,NaN,New York Jets / 3rd / 72nd pick / 2013
1,2,2013,Brennan Williams,OL,NaN,North Carolina,College Stats,6-Jun,6'6,318,5.27,NaN,NaN,NaN,NaN,NaN,Houston Texans / 3rd / 89th pick / 2013
2,3,2013,John Wetzel,OL,11,Boston College,NaN,7-Jun,6'7,315,5.46,25,22,105,7.9,4.81,NaN
3,4,2013,Jason Weaver,OL,NaN,Southern Miss,NaN,4-Jun,6'4,313,5.44,21,23,94,8.23,5.07,NaN
4,5,2013,Menelik Watson,OL,12,Florida State,NaN,5-Jun,6'5,310,5.29,24.5,NaN,103,8.31,5.01,Oakland Raiders / 2nd / 42nd pick / 2013

In [4]:
import os
dirs = os.listdir( "./Resources" )

filenames = []
# This would print all the files and directories
for file in dirs:
  #print(file)
    filenames.append(file)

filenames

['OL2010_2013.csv',
 '.DS_Store',
 'WR2010_2013.csv',
 'WR2014_2015.csv',
 'OL2014_2015.csv',
 'TE2010_2015.csv']

In [12]:
combined_wrestlers_df['Pos'] = combined_wrestlers_df['Pos'].replace(
   {'OG': 'OL', 'OT': 'OL'})
combined_wrestlers_df.head()

,Rk,Year,Player,Pos,AV,School,College,HE,Height,Wt,40YD,Vertical,BenchReps,Broad Jump,3Cone,Shuttle,Drafted (tm/rnd/yr)
0,1,2013,Brian Winters,OL,27.0,Kent State,NaN,4-Jun,6'4,320,5.22,NaN,9.0,NaN,NaN,NaN,New York Jets / 3rd / 72nd pick / 2013
1,2,2013,Brennan Williams,OL,NaN,North Carolina,College Stats,6-Jun,6'6,318,5.27,NaN,NaN,NaN,NaN,NaN,Houston Texans / 3rd / 89th pick / 2013
2,3,2013,John Wetzel,OL,11.0,Boston College,NaN,7-Jun,6'7,315,5.46,25.0,22.0,105.0,7.90,4.81,NaN
3,4,2013,Jason Weaver,OL,NaN,Southern Miss,NaN,4-Jun,6'4,313,5.44,21.0,23.0,94.0,8.23,5.07,NaN
4,5,2013,Menelik Watson,OL,12.0,Florida State,NaN,5-Jun,6'5,310,5.29,24.5,NaN,103.0,8.31,5.01,Oakland Raiders / 2nd / 42nd pick / 2013